"""Source-linked editorial guides with a labelled Lumo affiliate advertisement."""
from html import escape
from meeting_content import GUIDES as MEETING_GUIDES, publish_meeting_pages
from muse_content import MUSE_CARD, publish_muse

TOOLS = [
    dict(slug='cursor', name='Cursor', category='AI coding',
         summary='An editor-based coding assistant with a free Hobby plan and paid individual and team options.',
         facts='The official pricing page lists limited Agent requests on Hobby. Paid plans include model usage, with additional on-demand usage billed separately. Subscriptions are sold directly by Cursor.',
         advice='Try a small change in an existing project before subscribing. Check the diff and run your tests. Decide whether the included usage matches your workload before enabling extra spend.',
         limits='A subscription does not mean unlimited use of every model. Check model usage, additional billing and taxes. Avoid unofficial subscription resellers.',
         source='https://cursor.com/pricing'),
    dict(slug='github-copilot', name='GitHub Copilot', category='AI coding',
         summary='A coding assistant with a Free plan and paid plans, useful to evaluate alongside your existing editor and GitHub workflow.',
         facts='The official plan comparison distinguishes limited free chat and agent usage from paid plans. Included AI credits, additional credit purchases and access to cloud-agent features vary by plan.',
         advice='Use the Free plan to check your editor workflow first. Compare the features you actually need: local assistance, pull-request reviews or delegated work. Do not pay for team features solely because they appear in the comparison table.',
         limits='Usage allowances and supported features can change. Review the current plan comparison before paying; a coding subscription is separate from your website hosting bill.',
         source='https://github.com/features/copilot/plans'),
    dict(slug='hostinger-ai-builder', name='Hostinger AI Builder', category='AI website building',
         summary='An AI-powered website and application builder to consider when you want to build a site with prompts rather than maintain your own server stack.',
         facts='Hostinger describes Manual and Agentic building modes. Its hosting documentation says the builder is included with eligible hosting plans and is not compatible with VPS hosting.',
         advice='Write down the site features you need before choosing a plan: a simple information site and an application with stored user data are different projects. Verify plan eligibility and what happens to your site when you cancel.',
         limits='Do not assume an existing VPS purchase includes the builder. Confirm the total checkout term, renewal charge, domain conditions and any usage limits.',
         source='https://www.hostinger.com/ai-website-builder',
         extra='https://www.hostinger.com/support/hostinger-ai-builder-hosting-requirements/'),
    dict(slug='hugging-face-inference-endpoints', name='Hugging Face Inference Endpoints', category='AI infrastructure',
         summary='Managed model deployment for applications that need an inference endpoint rather than an editor subscription.',
         facts='The official documentation describes managed infrastructure and autoscaling that increases capacity with traffic and reduces it when traffic falls.',
         advice='Start by defining the model, latency target and expected request pattern. Compare a managed endpoint with operating your own model server, including maintenance time. Validate the model on representative input before choosing hardware.',
         limits='Autoscaling is not a guarantee of a zero bill. Check hardware pricing, idle behavior, scaling configuration and model licensing. An ordinary VPS offer is not proof that a machine can run your model.',
         source='https://huggingface.co/docs/inference-endpoints/index'),
]

def publish_ai_pages(page, cfg):
    date=cfg.get('ai_content_updated','2026-10-02')
    hub_date=cfg.get('ai_hub_updated',date)
    def publish(path,title,description,body,lastmod=None):
        page(path,title,description,body,lastmod=lastmod or date)
    cards=''.join(f'<article class="card"><p class="eyebrow">{escape(t["category"])}</p><h3><a href="/ai-tools/{t["slug"]}/">{escape(t["name"])}</a></h3><p>{escape(t["summary"])}</p><a class="arrow" href="/ai-tools/{t["slug"]}/">Read the buying guide →</a></article>' for t in TOOLS)
    rows=''.join(f'<tr><td><a href="/ai-tools/{t["slug"]}/">{escape(t["name"])}</a></td><td>{escape(t["category"])}</td><td>{escape(t["limits"])}</td></tr>' for t in TOOLS)
    meeting_cards=''.join(f'<article class="card"><p class="eyebrow">AI WORKFLOW</p><h3><a href="/ai-tools/{slug}/">{escape(title)}</a></h3><p>{escape(description)}</p></article>' for slug,title,description,_ in MEETING_GUIDES)
    task_routes=(
        '<section class="section" id="task-routes"><div class="section-heading"><h2>Start with the task, then choose a tool</h2><a href="/free-ai/">Compare free entry points →</a></div>'
        '<p>Pick the checkpoint that matches the work in front of you. Each route includes an input, a finish condition and a check you can perform yourself.</p><div class="grid task-grid">'
        '<article class="card"><p class="eyebrow">WRITE</p><h3><a href="/start/">Turn notes into a checked draft</a></h3><p>Keep facts, missing details and the action you control separate.</p></article>'
        '<article class="card"><p class="eyebrow">READ A PDF</p><h3><a href="/ai-tools/scanned-pdf-to-text/">Prepare readable document text</a></h3><p>Decide whether OCR is needed, preserve page labels and verify extracted values.</p></article>'
        '<article class="card"><p class="eyebrow">FINISH A FILE</p><h3><a href="/ai-tools/check-free-ai-export/">Save, reopen and edit the result</a></h3><p>Test the destination with a small fictional fixture before relying on it.</p></article>'
        '<article class="card"><p class="eyebrow">LIMIT REACHED</p><h3><a href="/ai-tools/save-free-ai-progress/">Save progress before access stops</a></h3><p>Keep source-labelled input, checked facts, the unfinished draft and one next action.</p></article>'
        '<article class="card"><p class="eyebrow">MEETING</p><h3><a href="/ai-tools/ai-meeting-notes/">Plan a meeting-notes handoff</a></h3><p>Define capture, correction, decisions, owners and the export destination.</p></article>'
        '<article class="card"><p class="eyebrow">COMPARE PLANS</p><h3><a href="/free-ai/">Check what “free” covers</a></h3><p>Separate a free app, a limited plan, a trial and paid API usage.</p></article>'
        '</div></section>')
    lumo_ad=(
        '<section class="section" id="lumo-affiliate"><p class="eyebrow">AFFILIATE ADVERTISEMENT</p>'
        '<h2>Considering Lumo for your next AI task?</h2>'
        '<p>Review Proton Lumo’s current features, plans and usage limits before choosing an AI assistant.</p>'
        '<p><a class="button" href="https://xmknb.com/g/0crpj4qh4nb059e94582a413d45360/" rel="sponsored noopener">Explore Lumo plans →</a></p>'
        '<p>We may earn a commission on qualifying purchases through this link.</p>'
        '<p>This link uses an affiliate redirect. See our <a href="/privacy/#affiliate-links">privacy policy</a> before following it.</p></section>')
    publish('/ai-tools/','AI tools for developers and website builders','Source-linked AI task guides, free entry points and buying checks.',
        '<section class="page-hero task-hero"><p class="eyebrow">AI TOOLS</p><h1>Choose the task.<br><span>Then choose the tool.</span></h1><p class="lede">Start with what must be finished: a checked draft, readable PDF, editable file, saved handoff or meeting record. Use the task routes below before comparing products or plans.</p><div class="task-links"><a href="#task-routes">Find a workflow</a><a href="/free-ai/">Compare free access</a><a href="#product-guides">Browse product guides</a></div></section>'
        +task_routes+lumo_ad+
        '<div class="notice">No verified promotional coupon is listed in this collection. Free plans and standard subscriptions are not discounts. Product links go directly to official sites; no affiliate commission is configured for product listings. This collection page contains a labelled Lumo affiliate advertisement. Three workflow guides also contain a labelled affiliate advertisement.</div>'
        '<section class="section" id="product-guides"><div class="section-heading"><h2>Product guides</h2><a href="#task-routes">Back to task routes ↑</a></div><div class="grid">'+cards+MUSE_CARD+'</div></section><section class="section"><h2>Choose by the work, not the label</h2><div class="table-wrap"><table><thead><tr><th>Tool</th><th>Use case</th><th>Before you pay</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>'
        '<section class="section"><h2>Meeting notes, transcription and summaries</h2><p>Choose a tool around capture, correction, export and access. These independent workflow guides help you evaluate the complete handoff before subscribing.</p><div class="grid">'+meeting_cards+'</div></section>'
        '<section class="prose"><h2>Practical guides</h2><p><a href="/ai-tools/check-ai-citations/">Check cited evidence before using an AI answer</a></p><p><a href="/ai-tools/coding-assistant-checklist/">Choose an AI coding assistant without buying overlapping subscriptions</a></p><p><a href="/ai-tools/ai-app-budget/">Plan an AI app budget: tools, hosting and model usage</a></p><p><a href="/ai-tools/check-free-ai-export/">Check whether a result stays usable after export</a></p><p><a href="/ai-tools/save-free-ai-progress/">Build a handoff before a free usage limit interrupts the task</a></p><h2>How we review</h2><p>Product facts are based on the linked official sources. Buying advice is our editorial judgment, not a benchmark or a claim of hands-on testing. This collection is manually reviewed and is separate from the automated VPS price monitor. Product source review date: '+escape(date)+'. Task hub review date: '+escape(hub_date)+'. Check the official page before purchase.</p></section>',lastmod=hub_date)
    publish_meeting_pages(page,cfg.get('meeting_content_updated','2026-10-03'))
    publish_muse(page)
    for t in TOOLS:
        extra=f'<li><a href="{escape(t["extra"])}" rel="noopener">Official hosting requirements</a></li>' if t.get('extra') else ''
        body=f'<section class="page-hero"><p class="eyebrow">{escape(t["category"])}</p><h1>{escape(t["name"])}: what to check before buying</h1><p class="lede">{escape(t["summary"])}</p></section><article class="prose"><h2>What the official source confirms</h2><p>{escape(t["facts"])}</p><h2>Our buying advice</h2><p>{escape(t["advice"])}</p><h2>Costs and limitations</h2><p>{escape(t["limits"])}</p><h2>Is there a verified coupon?</h2><p>We have not verified a promotional coupon for this listing. Check the official source for current offers and eligibility. A free plan is not a discount on a paid subscription.</p><h2>Official sources</h2><ul><li><a href="{escape(t["source"])}" rel="noopener">Official product information and terms</a></li>{extra}</ul><p>Source review date: {escape(date)}. Editorial advice; no hands-on performance test is claimed. Direct official links, with no affiliate commission configured.</p><p><a href="/ai-tools/">← All AI tools</a> · <a href="/ai-tools/ai-app-budget/">Plan your project budget</a></p></article>'
        publish('/ai-tools/'+t['slug']+'/',t['name']+' buying guide | '+cfg['brand'],t['summary'],body)
    publish('/ai-tools/coding-assistant-checklist/','How to choose an AI coding assistant','A practical evaluation checklist for Cursor and GitHub Copilot.',
        '<section class="page-hero"><p class="eyebrow">BUYING GUIDE</p><h1>Choose a coding assistant before another subscription.</h1><p class="lede">Start with the editor you use and a real task. A feature list cannot tell you whether a tool fits your project.</p></section><article class="prose"><h2>Use a task you can verify</h2><p>Choose a bounded job such as fixing a known bug or adding validation to a form. Save the starting state in version control, define the expected result and run your existing checks afterward. Compare the amount of code you had to correct and whether you understood the final change. This is a suggested evaluation method, not a published benchmark.</p><h2>Compare workflow before price</h2><p><a href="/ai-tools/cursor/">Cursor</a> is worth examining if you want an editor centered on agent-assisted work. <a href="/ai-tools/github-copilot/">GitHub Copilot</a> is worth examining if you want assistance within your existing editor and GitHub workflow. Confirm support for your environment on the official product pages.</p><h2>Write down your stopping rule</h2><p>Before activating paid usage, choose a spending limit and decide which tasks justify it. Check whether exceeding included usage stops work or creates another charge. Review renewal and cancellation terms. Avoid buying overlapping plans until you can name the different job each one does.</p><h2>What counts as value?</h2><p>Keep a short log of completed tasks and time spent reviewing output. A tool that produces more code can still create more maintenance. Prefer changes you can test, explain and maintain. Never use production secrets as trial input.</p><p>Official facts and source links: <a href="/ai-tools/cursor/">Cursor guide</a> and <a href="/ai-tools/github-copilot/">Copilot guide</a>. Recommendations here are editorial judgment, not measured productivity claims.</p></article>')
    publish('/ai-tools/ai-app-budget/','AI app budget: tools, hosting and model usage','Separate development subscriptions, hosting and inference costs before buying.',
        '<section class="page-hero"><p class="eyebrow">AI + HOSTING</p><h1>Your coding subscription is only part of the budget.</h1><p class="lede">Separate the cost of building an application from the cost of running it for visitors.</p></section><article class="prose"><h2>Keep separate budget lines</h2><p>List development tools, hosting, model inference, storage and domain renewal separately. A coding assistant helps you build; it does not automatically pay the model bill for your deployed app. An AI website builder may bundle some hosting, so check what is included before adding a VPS.</p><h2>Match the deployment to the workload</h2><p>For a static information site, first ask whether server hosting is needed at all. For an app that calls a hosted model, check API billing and where credentials will be stored. For a self-hosted model, investigate memory, accelerator support and concurrency rather than selecting a server from its introductory price alone.</p><h2>Plan for quiet and busy periods</h2><p><a href="/ai-tools/hugging-face-inference-endpoints/">Managed endpoints</a> offer autoscaling, but inspect the configuration and billing conditions. For any usage-based service, ask what happens when a visitor repeats a request, uploads a large file or triggers retries. Decide which limits can be enforced by the application before launch.</p><h2>Compare full terms</h2><p>Use <a href="/compare/">our VPS comparison</a> to inspect verified hosting offers. Then check renewal pricing, commitment length and cancellation. For <a href="/ai-tools/hostinger-ai-builder/">an AI builder</a>, confirm the eligible plan and any limits on generated changes. These are different purchases; a cheap server is not automatically the cheapest working solution.</p><h2>Before paying</h2><p>Write a conservative budget with separate fixed and variable costs, choose a spending ceiling and test representative requests. Do not treat promotional credits as permanent operating income. No cost estimate or savings percentage is claimed in this guide.</p><p>This is editorial planning advice. Consult the official source links in the product guides for current product conditions.</p></article>')
