"""Source-linked editorial guides with a labelled Lumo affiliate advertisement."""
from html import escape
from meeting_content import GUIDES as MEETING_GUIDES, publish_meeting_pages
from muse_content import MUSE_CARD, publish_muse

TOOLS = [
    dict(slug='cursor', name='Cursor', category='AI coding',
         summary='An editor-based coding assistant with a free Hobby plan and paid individual and team options.',
         facts='The official pricing page lists limited Agent requests on Hobby. Paid plans include model usage, with additional on-demand usage billed separately. Subscriptions are sold directly by Cursor.',
         advice='Try fixing one bug in a project you know. Read the diff and run the tests before keeping the change. Check the included usage before turning on extra billing.',
         limits='A subscription does not mean unlimited use of every model. Check model usage, additional billing and taxes. Avoid unofficial subscription resellers.',
         source='https://cursor.com/pricing'),
    dict(slug='github-copilot', name='GitHub Copilot', category='AI coding',
         summary='A coding assistant with a Free plan and paid plans, for use in your editor and GitHub workflow.',
         facts='The official plan comparison distinguishes limited free chat and agent usage from paid plans. Included AI credits, additional credit purchases and access to cloud-agent features vary by plan.',
         advice='Try Free in the editor you already use. Then decide what is missing: code suggestions, pull-request reviews or an agent that takes on a task. Pay for the missing feature, rather than the longest feature list.',
         limits='Usage allowances and supported features can change. Review the current plan comparison before paying; a coding subscription is separate from your website hosting bill.',
         source='https://github.com/features/copilot/plans'),
    dict(slug='hostinger-ai-builder', name='Hostinger AI Builder', category='AI website building',
         summary='An AI-powered website and application builder to consider when you want to build a site with prompts rather than maintain your own server stack.',
         facts='Hostinger describes Manual and Agentic building modes. Its hosting documentation says the builder is included with eligible hosting plans and is not compatible with VPS hosting.',
         advice='List what the site needs to do. A few information pages need less setup than an app that stores user data. Before paying, check which plan includes the builder and whether you can take your site elsewhere.',
         limits='Do not assume an existing VPS purchase includes the builder. Confirm the total checkout term, renewal charge, domain conditions and any usage limits.',
         source='https://www.hostinger.com/ai-website-builder',
         extra='https://www.hostinger.com/support/hostinger-ai-builder-hosting-requirements/'),
    dict(slug='hugging-face-inference-endpoints', name='Hugging Face Inference Endpoints', category='AI infrastructure',
         summary='Managed model deployment for applications that need an inference endpoint rather than an editor subscription.',
         facts='The official documentation describes managed infrastructure and autoscaling that increases capacity with traffic and reduces it when traffic falls.',
         advice='Choose the model and try the inputs your app will receive. Note how quickly it needs to respond and how many requests may arrive together. Compare a managed endpoint with running the server yourself, including the time needed to maintain it.',
         limits='Autoscaling is not a guarantee of a zero bill. Check hardware pricing, idle behavior, scaling configuration and model licensing. An ordinary VPS offer is not proof that a machine can run your model.',
         source='https://huggingface.co/docs/inference-endpoints/index'),
]

def publish_ai_pages(page, cfg):
    date=cfg.get('ai_content_updated','2026-10-02')
    hub_date='2026-10-11'
    def publish(path,title,description,body,lastmod=None):
        page(path,title,description,body,lastmod=lastmod or '2026-10-07')
    cards=''.join(f'<article class="card"><p class="eyebrow">{escape(t["category"])}</p><h3><a href="/ai-tools/{t["slug"]}/">{escape(t["name"])}</a></h3><p>{escape(t["summary"])}</p><a class="arrow" href="/ai-tools/{t["slug"]}/">Read the buying guide →</a></article>' for t in TOOLS)
    rows=''.join(f'<tr><td><a href="/ai-tools/{t["slug"]}/">{escape(t["name"])}</a></td><td>{escape(t["category"])}</td><td>{escape(t["limits"])}</td></tr>' for t in TOOLS)
    meeting_cards=''.join(f'<article class="card"><p class="eyebrow">AI WORKFLOW</p><h3><a href="/ai-tools/{slug}/">{escape(title)}</a></h3><p>{escape(description)}</p></article>' for slug,title,description,_ in MEETING_GUIDES)
    task_routes=(
        '<section class="section" id="task-routes"><div class="section-heading"><h2>Start with the task, then choose a tool</h2><a href="/free-ai/">Compare free entry points →</a></div>'
        '<p>Choose the job below. Each guide shows what to prepare, what to do and how to check the result.</p><div class="grid task-grid">'
        '<article class="card"><p class="eyebrow">WRITE</p><h3><a href="/start/">Turn notes into a draft you can use</a></h3><p>Keep facts, missing details and the action you control separate.</p></article>'
        '<article class="card"><p class="eyebrow">READ A PDF</p><h3><a href="/ai-tools/scanned-pdf-to-text/">Prepare readable document text</a></h3><p>Decide whether OCR is needed, preserve page labels and verify extracted values.</p></article>'
        '<article class="card"><p class="eyebrow">FINISH A FILE</p><h3><a href="/ai-tools/check-free-ai-export/">Save, reopen and edit the result</a></h3><p>Save a sample, reopen it and try the edits you need.</p></article>'
        '<article class="card"><p class="eyebrow">LIMIT REACHED</p><h3><a href="/ai-tools/save-free-ai-progress/">Save progress before access stops</a></h3><p>Save your source notes, checked facts, draft and the next step.</p></article>'
        '<article class="card"><p class="eyebrow">MEETING</p><h3><a href="/ai-tools/ai-meeting-notes/">Make meeting notes your team can use</a></h3><p>Check the recording, correct the notes and save decisions with their owners.</p></article>'
        '<article class="card"><p class="eyebrow">COMPARE PLANS</p><h3><a href="/free-ai/">Check what “free” covers</a></h3><p>Separate a free app, a limited plan, a trial and paid API usage.</p></article>'
        '</div></section>')
    lumo_ad=(
        '<section class="section" id="lumo-affiliate"><p class="eyebrow">AFFILIATE ADVERTISEMENT</p>'
        '<h2>Considering Lumo for your next AI task?</h2>'
        '<p>Review Proton Lumo’s current features, plans and usage limits before choosing an AI assistant.</p>'
        '<p><a class="button" href="https://xmknb.com/g/0crpj4qh4nb059e94582a413d45360/" rel="sponsored noopener">Explore Lumo plans →</a></p>'
        '<p>We may earn a commission on qualifying purchases through this link.</p>'
        '<p>This link uses an affiliate redirect. See our <a href="/privacy/#affiliate-links">privacy policy</a> before following it.</p></section>')
    publish('/ai-tools/','AI tools for writing, documents, meetings and coding | '+cfg['brand'],'Practical AI workflows, free entry points and product guides for everyday tasks.',
        '<section class="page-hero task-hero"><p class="eyebrow">AI TOOLS</p><h1>Choose the task.<br><span>Then choose the tool.</span></h1><p class="lede">What are you trying to finish: a draft, a PDF, a spreadsheet or meeting notes? Start there. Choose a product after you know what the job needs.</p><div class="task-links"><a href="#task-routes">Find a workflow</a><a href="/free-ai/">Compare free access</a><a href="#product-guides">Browse product guides</a></div></section>'
        +task_routes+lumo_ad+
        '<div class="notice">Product listings link directly to official sites. The Lumo advertisement here and advertisements in three workflow guides are labelled and disclosed. We list no verified coupons; a free plan is not a paid-plan discount.</div>'
        '<section class="section" id="product-guides"><div class="section-heading"><h2>Product guides</h2><a href="#task-routes">Back to task routes ↑</a></div><div class="grid">'+cards+MUSE_CARD+'</div></section><section class="section"><h2>Which tool fits the job?</h2><div class="table-wrap"><table><thead><tr><th>Tool</th><th>Use case</th><th>Before you pay</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>'
        '<section class="section"><h2>Meeting notes, transcription and summaries</h2><p>Need a transcript, a summary or a list of decisions? These guides walk through recording, corrections and saving the result.</p><div class="grid">'+meeting_cards+'</div></section>'
        '<section class="prose"><h2>Practical guides</h2><p><a href="/ai-tools/keep-zero-blank-unknown/">Keep zero, blank and UNKNOWN separate in exported tables</a></p><p><a href="/ai-tools/ask-about-missing-details/">Ask one useful follow-up when a detail is missing</a></p><p><a href="/ai-tools/check-ai-source-updates/">Check source versions after a document changes</a></p><p><a href="/ai-tools/check-ai-citations/">Check cited evidence before using an AI answer</a></p><p><a href="/ai-tools/coding-assistant-checklist/">Choose an AI coding assistant without buying overlapping subscriptions</a></p><p><a href="/ai-tools/ai-app-budget/">Plan an AI app budget: tools, hosting and model usage</a></p><p><a href="/ai-tools/check-free-ai-export/">Check a file after exporting it</a></p><p><a href="/ai-tools/save-free-ai-progress/">Save your work before you hit a free usage limit</a></p><h2>How we review</h2><p>Product details come from the official sources linked in each guide. These are buying guides, not performance tests. We update them manually; VPS price checks run separately. Product source review date: '+escape(date)+'. Task hub review date: '+escape(hub_date)+'. Check the official page before purchase.</p></section>',lastmod=hub_date)
    publish_meeting_pages(page,cfg.get('meeting_content_updated','2026-10-03'))
    publish_muse(page)
    for t in TOOLS:
        extra=f'<li><a href="{escape(t["extra"])}" rel="noopener">Official hosting requirements</a></li>' if t.get('extra') else ''
        body=f'<section class="page-hero"><p class="eyebrow">{escape(t["category"])}</p><h1>{escape(t["name"])}: what to check before buying</h1><p class="lede">{escape(t["summary"])}</p></section><article class="prose"><h2>What the plan includes</h2><p>{escape(t["facts"])}</p><h2>Try this before paying</h2><p>{escape(t["advice"])}</p><h2>Check the costs and limits</h2><p>{escape(t["limits"])}</p><h2>Official sources</h2><ul><li><a href="{escape(t["source"])}" rel="noopener">Official product information and terms</a></li>{extra}</ul><p>Source review date: {escape(date)}. Based on product documentation, not a performance test. Source links are not affiliate links.</p><p><a href="/ai-tools/">← All AI tools</a> · <a href="/ai-tools/ai-app-budget/">Plan your project budget</a></p></article>'
        publish('/ai-tools/'+t['slug']+'/',t['name']+' buying guide | '+cfg['brand'],t['summary'],body)
    publish('/ai-tools/coding-assistant-checklist/','How to choose an AI coding assistant','A practical evaluation checklist for Cursor and GitHub Copilot.',
        '<section class="page-hero"><p class="eyebrow">BUYING GUIDE</p><h1>Which coding assistant should you pay for?</h1><p class="lede">Try one small job in your usual editor before subscribing. Keep the tool that makes the job easier to review and maintain.</p></section><article class="prose"><h2>Use a task you can verify</h2><p>Pick a known bug or add one form check. Commit the starting code, write down the expected behaviour and run the tests after the assistant finishes. Read the diff: how much did you correct, and can you explain the code you kept?</p><h2>Compare workflow before price</h2><p><a href="/ai-tools/cursor/">Cursor</a> is worth examining if you want an editor centered on agent-assisted work. <a href="/ai-tools/github-copilot/">GitHub Copilot</a> is worth examining if you want assistance within your existing editor and GitHub workflow. Confirm support for your environment on the official product pages.</p><h2>Write down your stopping rule</h2><p>Before activating paid usage, choose a spending limit and decide which tasks justify it. Check whether exceeding included usage stops work or creates another charge. Review renewal and cancellation terms. Avoid buying overlapping plans until you can name the different job each one does.</p><h2>Was it worth using?</h2><p>Keep a short log of completed tasks and time spent reviewing output. Count the review work as well as the code written. Keep changes you can test and explain. Never use production secrets as trial input.</p><p>Official facts and source links: <a href="/ai-tools/cursor/">Cursor guide</a> and <a href="/ai-tools/github-copilot/">Copilot guide</a>. This checklist is a suggested trial, not a comparison of measured productivity.</p></article>')
    publish('/ai-tools/ai-app-budget/','AI app budget: tools, hosting and model usage','Separate development subscriptions, hosting and inference costs before buying.',
        '<section class="page-hero"><p class="eyebrow">AI + HOSTING</p><h1>Your coding subscription is only part of the budget.</h1><p class="lede">Separate the cost of building an application from the cost of running it for visitors.</p></section><article class="prose"><h2>Keep separate budget lines</h2><p>List development tools, hosting, model inference, storage and domain renewal separately. A coding assistant helps you build; it does not automatically pay the model bill for your deployed app. An AI website builder may bundle some hosting, so check what is included before adding a VPS.</p><h2>Match the deployment to the workload</h2><p>For a static information site, first ask whether server hosting is needed at all. For an app that calls a hosted model, check API billing and where credentials will be stored. For a self-hosted model, investigate memory, accelerator support and concurrency rather than selecting a server from its introductory price alone.</p><h2>Plan for quiet and busy periods</h2><p><a href="/ai-tools/hugging-face-inference-endpoints/">Managed endpoints</a> offer autoscaling, but inspect the configuration and billing conditions. Check the bill for repeated requests, large uploads and retries. Set limits in the app before visitors can use it.</p><h2>Compare full terms</h2><p>Use <a href="/compare/">our VPS comparison</a> to inspect verified hosting offers. Then check renewal pricing, commitment length and cancellation. For <a href="/ai-tools/hostinger-ai-builder/">an AI builder</a>, confirm the eligible plan and any limits on generated changes. These are different purchases; a cheap server is not automatically the cheapest working solution.</p><h2>Before paying</h2><p>Put fixed fees and usage charges on separate lines. Set a spending limit and try a few typical requests. Work out what you will pay when any promotional credits end.</p><p>Use the official links in the product guides to fill in current rates; this guide supplies no price estimates.</p></article>')
