"""Beginner advice and dated official-source free entry points."""
def publish_beginner_pages(page, cfg):
    page('/start/', 'Start using AI: your first useful task | '+cfg['brand'], 'Write a brief, check an AI draft and keep actions under your control.', '''
<section class="page-hero"><p class="eyebrow">START HERE</p><h1>Your first useful AI task</h1><p class="lede">Choose a small task whose result you can check. Start with a draft.</p></section><article class="prose">
<h2>Choose a task with a clear finish</h2><p>Try reorganising your own notes, outlining an article or drafting a routine message. Write down what a useful result looks like before opening a tool. Work on a copy and remove private identifiers. For a first exercise, avoid payments, account changes and decisions you cannot independently verify.</p>
<h2>Give a brief, not just a topic</h2><p>Specify the audience, input, output and limits. Ask the assistant to identify missing information rather than invent facts.</p><blockquote>Turn the notes below into a short project update for a colleague. Use only facts in the notes. Separate completed work, blockers and next steps. If a date or owner is missing, mark it unknown. Do not send the message.</blockquote><p>This is a reusable prompt example, not a verified product benchmark.</p>
<h2>Check the draft against the input</h2><ol><li>Compare names, dates, numbers and promises with your original notes.</li><li>Remove unsupported additions. Open cited sources and check that they support the claims.</li><li>Request one specific correction, such as separating a proposed deadline from an agreed deadline.</li><li>Review the final version yourself before sending or publishing it.</li></ol>
<h2>Keep actions under your control</h2><p>A chatbot drafts text; an agent may also use tools and change files or accounts. Check the permissions, which destination receives your data, and whether an action can be undone. Approve concrete actions after reviewing the result. Never include passwords or identity documents in a public example.</p>
<h2>Decide whether you need a paid plan</h2><p>Test a free entry point on representative work first. Record which limit blocks completion: input size, usage, export or integration. Evaluate a paid plan when it solves that specific limit. Paying does not remove the need to check the output.</p>
<h2>Keep a practice record</h2><p>Record the task, non-sensitive input, tool and version if shown, corrections and final result. Include failures and manual work. This supports a reproducible case study; it is not evidence of earnings or guaranteed time savings.</p><p><a href="/free-ai/">Free entry points</a> · <a href="/ai-tools/meta-muse-guide/">Muse beginner guide</a> · <a href="/ai-tools/verify-ai-meeting-summaries/">Verify a meeting summary</a></p><p>This guide is editorial workflow advice, not a hands-on model evaluation.</p></article>''', lastmod='2026-10-03')
    page('/free-ai/', 'Free AI entry points: limits and sources | '+cfg['brand'], 'Official-source free AI plans with dated checks and clearly stated limits.', '''
<section class="page-hero"><p class="eyebrow">FREE AI</p><h1>Try the workflow.<br><span>Understand the limits.</span></h1><p class="lede">Free entry points to tools do not make every underlying model or API free.</p></section>
<section class="section"><div class="table-wrap"><table><thead><tr><th>Tool / plan</th><th>Access type</th><th>Limits to check</th><th>Source / reviewed</th></tr></thead><tbody>
<tr><td><a href="/ai-tools/github-copilot/">GitHub Copilot Free</a></td><td>Free AI coding plan</td><td>Limited chat and agent usage. Feature access differs from paid plans; check your editor and eligibility.</td><td><a href="https://github.com/features/copilot/plans" rel="noopener">Official plan comparison</a><br>Listed as available<br>Reviewed 2026-10-03</td></tr>
<tr><td><a href="/ai-tools/cursor/">Cursor Hobby</a></td><td>Free entry plan for the Cursor editor</td><td>Limited usage. Not unlimited access to every model or a separate model-provider API subscription.</td><td><a href="https://cursor.com/pricing" rel="noopener">Official pricing</a><br>Listed as available<br>Reviewed 2026-10-03</td></tr>
</tbody></table></div></section><article class="prose"><h2>Read the conditions first</h2><p>A free plan, a timed trial, promotional credits and downloadable model weights are different things. Check region eligibility, payment-method requirements, renewal behaviour, data handling and the limit relevant to your task. These entries do not assert that no card is required; inspect the signup screen.</p><h2>Updates and history</h2><p>The date records a source review, not continuous monitoring. Current official conditions and your account screen take precedence. Changed or ended plans will retain a dated historical entry, an explicit status and a verified replacement when available. A failed source check means unverified, not ended.</p><p>No ended entries have been recorded yet. No affiliate commission is configured for these links.</p><p><a href="/start/">Start with one useful task</a> · <a href="/ai-tools/coding-assistant-checklist/">Choose a coding assistant</a> · <a href="/offers/">Verified offers</a></p></article>''', lastmod='2026-10-03')
