"""An original citation-check exercise, without product performance claims."""
TITLE = 'Check citations in free AI answers before using them'
DESCRIPTION = 'Open the cited passage, match it to the exact claim, and keep unsupported details out of your final answer.'
BODY = '''<section class="page-hero"><p class="eyebrow">FREE AI WORKFLOW</p><h1>Check citations before you use an AI answer</h1><p class="lede">A citation is a route to evidence. Open it, read the surrounding passage, and check whether it supports the exact claim. If the source is missing, incomplete or different, mark the claim unresolved instead of repeating it as fact.</p></section><article class="prose">
<h2>Start with the claim you will actually use</h2><p>Before sharing an answer from a free AI tool, choose the sentence that matters to your task. Split combined statements into separate claims: a launch date, an eligibility condition and an available feature may require different evidence. A link that supports one detail does not automatically support the rest of the sentence.</p><p>This guide is a review exercise, not a ranking of free tools. It does not require a paid subscription or a particular model. If your tool cannot open sources, use your own browser and record the exact passage manually. An inaccessible citation stays inaccessible; asking another model to agree does not repair that missing evidence.</p>
<figure class="editorial-figure"><img src="/assets/editorial/citation-review-route.svg" width="760" height="540" loading="lazy" alt="Citation review route: isolate the claim, open the source, compare the passage, then retain, repair or withhold the claim."><figcaption>Check the claim, not just the presence of a link.</figcaption></figure>
<h2>An official-source example</h2><p>Google's current <a href="https://support.google.com/gemininotebook/answer/16179559?hl=en" rel="noopener">Gemini Notebook chat help</a> describes source citations that let you inspect quoted material. Hovering shows the quoted text, and selecting a citation opens its location for context. Source selection also controls which notebook sources are used. Those controls help inspection; this guide does not claim they guarantee correctness. Check your actual interface before relying on this route. We have not performed a hands-on product accuracy test.</p>
<h2>Try this fictional two-source exercise</h2><div data-original="fixture"><p>Save these two short notes as separate files or clearly labelled blocks. They are authored for this exercise and describe an invented workshop, not a real event. You can paste them into a text tool you already use; remove personal information from any real material you later substitute.</p>
<blockquote>Source A — Cedar workshop draft, 2026-10-01.<br>The workshop is proposed for 2026-10-20. Capacity is 18 attendees. The venue is awaiting approval. Registration is not open. Draft owner: Mara.</blockquote>
<blockquote>Source B — Cedar workshop update, 2026-10-06.<br>The approved workshop date is 2026-10-22. Capacity remains 18 attendees. The venue is approved. Registration opens only after the accessibility checklist is signed. The checklist owner has not been assigned.</blockquote>
<p>Ask: “Using only these two labelled sources, write the current date, capacity, venue status and registration condition. Identify the source and supporting passage for each claim. Distinguish the draft from the later update. Leave missing owners unknown. Do not add an external registration link.” Keep the input files and the answer together.</p><p>This prompt is a reusable inspection brief. It does not promise that the model will follow it. If the tool gives only a source label, locate the supporting sentence yourself. Record that you added the passage manually rather than presenting the model's unsupported reference as verified.</p></div>
<h2>Use the answer key to inspect the draft</h2><div data-original="answer-key"><div class="table-wrap"><table><thead><tr><th>Claim</th><th>Expected evidence</th><th>Decision</th></tr></thead><tbody>
<tr><td>Date is October 22</td><td>Source B states the approved date; Source A contains the earlier proposal.</td><td>Retain with the later source.</td></tr>
<tr><td>Capacity is 18</td><td>Both sources say 18; Source B says it remains unchanged.</td><td>Retain without implying expansion.</td></tr>
<tr><td>Venue is approved</td><td>Source B explicitly updates the venue status.</td><td>Retain; do not use the older pending status.</td></tr>
<tr><td>Registration is open now</td><td>Neither source says this. Source B makes opening conditional on a signed checklist.</td><td>Repair to state the condition; opening is unconfirmed.</td></tr>
<tr><td>Mara owns the checklist</td><td>Source A names a draft owner, while Source B says the checklist owner is unassigned.</td><td>Remove the invented assignment.</td></tr>
</tbody></table></div>
<p>Compare every row with the saved notes. Do not accept a correct-looking sentence if its cited source contains only the older proposal. Conversely, a source that mentions the right date does not justify an added claim about registration. Record the exact unsupported addition before rewriting the sentence, so the correction is auditable.</p></div>
<figure class="editorial-figure"><img src="/assets/editorial/citation-review-card.svg" width="760" height="540" loading="lazy" alt="Citation review card with claim, source label and date, supporting passage, missing detail and final decision."><figcaption>Keep an unresolved claim visible until the evidence is available.</figcaption></figure>
<h2>Keep a small review record</h2><div data-original="review-record"><p>Use one row per claim in your own notes: claim as written; source label and revision date; exact supporting passage; missing or conflicting detail; decision; corrected sentence. For the registration row above, write: claim = open now; evidence = opens only after a signed checklist; missing = whether the checklist was signed; decision = withhold the opening claim.</p><p>A suitable correction is: “Registration depends on a signed accessibility checklist; the supplied update does not confirm that signing is complete.” This is an answer-key sentence for the fictional input, not an announcement about a real workshop. It preserves what is known without converting an absence of information into a negative claim.</p><p>If you review a real PDF, keep its page label beside the passage and compare it with the original file. If you review a web page, record the URL and the actual retrieval date. A search snippet can help locate evidence but is not a substitute for the full passage. When two sources conflict, preserve both versions until you can establish which applies; a newer timestamp alone does not prove a different document supersedes the one you need.</p></div>
<h2>Questions that come up during review</h2><details><summary>Does a working citation prove the sentence is true?</summary><p>No. It proves that a destination opens. Check whether the passage supports the subject, detail and conditions in the claim. A live link can still point to the wrong version or an unrelated passage.</p></details><details><summary>What if I cannot open the source?</summary><p>Mark that claim unverified and keep it out of a factual conclusion. Ask the source owner for an accessible copy where appropriate. Do not bypass access restrictions or invent the missing passage.</p></details><details><summary>Should I ask a second AI to check the first?</summary><p>You may use another draft to help find questions, but it is not the source evidence. Return to the original passage and retain a record of what it supports.</p></details>
<h2>Scope and further reading</h2><p>A <a href="https://www.reddit.com/r/notebooklm/comments/1veqt1q/citations_are_not_verification_what_is_your/" rel="noopener">public community discussion about citation spot-checks</a> asks how people review notebook reports. It is a user discussion, not official product documentation or our test result. Our two-source workshop fixture and answer key provide a separate exercise you can repeat.</p><p>For unreadable source pages, use the <a href="/ai-tools/scanned-pdf-to-text/">PDF text preparation guide</a>. Before sending the saved result, use the <a href="/ai-tools/check-free-ai-export/">export acceptance card</a>. For decisions and owners, use the <a href="/ai-tools/verify-ai-meeting-summaries/">meeting-summary checklist</a>.</p><p>Official source reviewed 2026-10-07. Fictional fixture, answer key, review record and diagrams created for this guide. No product performance or time-saving measurement is claimed. Direct source links; no affiliate advertisement is configured on this page.</p><p><a href="/ai-tools/">All AI tools and practical guides</a></p></article>'''

def publish_citation_guide(page, cfg):
    page('/ai-tools/check-ai-citations/', TITLE, DESCRIPTION, BODY, lastmod='2026-10-07')
