"""An original missing-details exercise with a worked follow-up record."""
TITLE = "Missing information in an AI answer: what to ask next"
DESCRIPTION = "Separate omitted facts, missing commitments and conflicting notes. Use a worked example to ask one useful follow-up."
BODY = '''<section class="page-hero task-hero"><p class="eyebrow">FREE AI TOOLS / MISSING DETAILS</p><h1>Missing a fact? Ask one useful follow-up.</h1><p class="lede">First look for the detail in your original notes. If it is there, correct the answer. If it is absent, keep it UNKNOWN and ask the person who can supply it. Conflicting notes need a decision about which applies. A plausible AI answer does not settle any of these questions.</p></section><article class="prose">
<h2>Find out what is actually missing</h2><p>Put the original input beside the draft. Check the specific field that blocks your next step: a date, an owner, an amount or approval. Searching the source yourself helps distinguish an omitted fact from a fact nobody supplied. Ask the tool to locate a passage when that is useful, then read the passage.</p><p>Google's <a href="https://support.google.com/gemininotebook/answer/16179559?hl=en" rel="noopener">current notebook chat instructions</a> describe selecting sources for a question and opening a citation to inspect its context. Those controls can help you inspect an answer. They do not replace a decision by the person responsible for a missing commitment. This guide does not test a particular account or promise that a prompt prevents mistakes.</p>
<figure class="editorial-figure"><img src="/assets/editorial/missing-detail-route.svg" width="760" height="820" alt="Present in the source: correct the draft. Absent: ask the responsible person. Conflicting: resolve which instruction applies. Unapproved: keep the action on hold."/><figcaption>Choose the next step from the evidence you have.</figcaption></figure>
<h2>A small practice brief</h2><div data-original="practice"><p>The following Linden repair-clinic notes are fictional. You can complete the exercise in a text editor. If you try them in a free AI tool, use these notes instead of private customer information.</p><blockquote>S1 — Linden clinic brief.<br>Date: 2026-10-24.<br>Booked visitors: 7.<br>Capacity: 9.<br>Equipment checklist: spare cables and two test lamps.<br>Volunteer coordinator: Lee.<br>Reminder sender: not assigned.<br>Send reminders only after venue approval.</blockquote><blockquote>S2 — Venue note.<br>The room request is pending.<br>A volunteer suggested sending reminders on October 20.<br>No reminder time has been agreed.</blockquote><p>Here is a deliberately faulty draft: “Lee will send reminders on October 20 for seven visitors. The venue is approved.” It also leaves out the equipment checklist. Read the two sources before deciding what to ask.</p><p>Lee coordinates volunteers, but neither note appoints Lee as the reminder sender. October 20 is a suggestion, not an agreed time. The venue is explicitly pending. The equipment list already exists in S1, so asking someone to provide that list again would create unnecessary work.</p></div>
<h2>Use the answer key</h2><div data-original="answer-key"><div class="table-wrap"><table><thead><tr><th>Field</th><th>Evidence</th><th>Next step</th></tr></thead><tbody>
<tr><td>Visitors</td><td>S1 says 7 booked, capacity 9.</td><td>Keep 7 booked. Derive 2 available places separately.</td></tr>
<tr><td>Equipment</td><td>S1 lists spare cables and two test lamps.</td><td>Restore the list in the draft; no follow-up needed.</td></tr>
<tr><td>Reminder sender</td><td>S1 says not assigned.</td><td>Keep UNKNOWN. Ask the coordinator to name the sender.</td></tr>
<tr><td>Reminder time</td><td>S2 contains a suggestion only.</td><td>Keep UNAGREED; do not convert October 20 into a commitment.</td></tr>
<tr><td>Venue approval</td><td>S2 says pending.</td><td>Correct the draft and leave reminders unsent.</td></tr>
</tbody></table></div><p>A checked update would read: “The clinic is planned for October 24, 2026. Seven visitors are booked, with two places available from capacity 9 minus 7. Bring spare cables and two test lamps. The reminder sender is not assigned and the reminder time is unagreed. Venue approval is pending, so reminders must remain unsent.”</p><p>Notice the different remedies: recover one omitted list, remove two invented commitments, correct one approval claim and preserve the unresolved fields. Asking “Can you add more detail?” would blur those jobs together. Compare your own revised draft with each row before moving on.</p></div>
<h2>Ask the smallest question that unlocks the task</h2><div data-original="follow-up"><p>In this exercise, assigning a reminder sender is a useful first question. Venue approval remains a separate condition; assigning a sender does not authorize sending. Address the question to Lee because the brief identifies Lee as the volunteer coordinator, not because Lee is already the sender.</p><blockquote>Lee, who should send the Linden clinic reminders? S1 leaves the sender unassigned. Please name the person or leave the field unassigned. This is an assignment question only; reminders remain unsent while venue approval is pending.</blockquote><p>Save a tiny follow-up record: field — reminder sender; current value — UNKNOWN; evidence — S1; asked — Lee; answer — pending; effect — update the draft only. You can write it outside the AI tool. Do not mark the field resolved merely because you have sent a question.</p><p>Suppose Lee replies, “Pat handles reminders; the time is still undecided.” Update the sender to Pat and preserve UNAGREED for the time. Keep the reply as evidence beside the revised brief. The venue condition still applies. A reply to one question should not silently resolve the others.</p></div>
<figure class="editorial-figure"><img src="/assets/editorial/one-followup-card.svg" width="760" height="590" loading="lazy" alt="Ask Lee to name the reminder sender. Record the reply only for that field. Keep the reminder time unagreed and the venue approval pending."/><figcaption>Update the answered field without inventing the rest.</figcaption></figure>
<h2>If the notes disagree</h2><div data-original="conflict"><p>Add a third fictional note: “S3 — Send reminders on October 19.” It has no approval or replacement statement. You now have conflicting instructions, not just a missing date. Do not let the assistant select the latest-looking date and call it agreed.</p><blockquote>Which reminder instruction applies to this clinic: S2's unagreed suggestion or S3's October 19 instruction? Please identify the approved instruction and whether it replaces the earlier note. Venue approval is still pending in S2.</blockquote><p>Keep both notes until their relationship is settled. Record who confirmed the applicable instruction and what changed. If nobody can confirm it, leave the reminder time unresolved and preserve the hold. The purpose is a traceable decision, not a more confident sentence.</p></div>
<h2>Questions you may have</h2><details><summary>Can I ask AI to make a reasonable assumption?</summary><p>For a planning sketch, label an assumption and keep it separate from known facts. Do not use a guessed owner, date or approval as a real commitment.</p></details><details><summary>Should I ask about every blank field?</summary><p>Start with the field needed for the next useful step. Keep other blanks visible. If no decision depends on a field yet, you can leave it unresolved.</p></details><details><summary>What if a free limit stops the chat?</summary><p>Save the source notes, checked draft and follow-up record in your own file. You can ask the responsible person directly. See the <a href="/ai-tools/save-free-ai-progress/">save-and-resume exercise</a>.</p></details>
<p>A <a href="https://www.reddit.com/r/notebooklm/comments/1shea80/how_can_i_make_the_ai_include_all_the_content/" rel="noopener">community question about omitted material</a> illustrates why checking coverage matters. It is an individual report, not an accuracy measurement.</p><p>Continue with <a href="/ai-tools/check-ai-citations/">checking cited passages</a>, <a href="/ai-tools/check-ai-source-updates/">checking changed sources</a> or <a href="/start/">your first useful AI task</a>.</p><h2>Sources and practice scope</h2><p>Official instructions reviewed 2026-10-09. The Linden notes, faulty draft, answer key, follow-up records and illustrations were created for this guide. They are worked examples, not observed product results. Source links are direct, non-affiliate links.</p></article>'''

def publish_clarification_guide(page, cfg):
    page("/ai-tools/ask-about-missing-details/", TITLE+" | "+cfg["brand"], DESCRIPTION, BODY, lastmod="2026-10-09")
