"""A worked source-version exercise for free AI research workflows."""
TITLE = 'Check updated sources before reusing an AI answer'
DESCRIPTION = 'Compare the original file, the AI source and the saved answer after a document changes. Practise with two versions and a worked update log.'
BODY = '''<section class="page-hero task-hero"><p class="eyebrow">FREE AI TOOLS / UPDATED DOCUMENTS</p><h1>Your document changed. Did your AI answer?</h1><p class="lede">Check three places before reusing an answer: the original document, the version available to the AI tool, and the file you will share. Updating the first does not prove the other two match. Compare one changed detail, ask again using the current source, then check the saved result.</p></section><article class="prose">
<h2>Start with one detail that changed</h2><p>Open the document that now applies to your task. Choose a change you can recognize: a revised date, a different count or a newly assigned owner. Find that detail in the source available to your AI tool. If the versions disagree, fix the source mismatch before asking for a new summary. Keep the earlier file so you can explain the correction.</p>
<figure class="editorial-figure"><img src="/assets/editorial/source-version-route.svg" width="760" height="650" alt="Three places to compare: original document, AI source, and saved result. Check one changed detail in each."/><figcaption>Check the source copy as well as the file you will share.</figcaption></figure>
<h2>What Google's current instructions say</h2><p>Google's <a href="https://support.google.com/gemininotebook/answer/16215270?hl=en" rel="noopener">source help</a> says Drive imports update every few minutes and when you open your notebook. You can also open a source and use “Click to sync with Google Drive.” Losing access to the Drive file makes that source inaccessible. This describes Drive imports; do not assume every upload or web link behaves the same way.</p><p>Its <a href="https://support.google.com/gemininotebook/answer/16262519?hl=en" rel="noopener">notes help</a> describes exporting a note to a new Google Doc. Edits in that Doc do not sync back to the original note, and notebook sharing permissions do not carry over. Check the exported copy separately. These are documented behaviours, not an account-level sync test we performed.</p>
<h2>Try two versions of the same brief</h2><div data-original="version-exercise"><p>These Harbor workshop notes are invented for this exercise. Save each block with its version label. Version B explicitly replaces Version A for the workshop brief; a newer date alone would not establish that relationship in a real project.</p>
<blockquote>Version A — Harbor brief, 2026-10-06.<br>Workshop date: 2026-10-18.<br>Confirmed guests: 10.<br>Room capacity: 14.<br>Poster owner: Kai.<br>Send the guest email only after the venue is approved.</blockquote>
<blockquote>Version B — Harbor brief, 2026-10-08. Replaces Version A for this workshop.<br>Workshop date: 2026-10-21.<br>Confirmed guests: 12.<br>Room capacity: 14.<br>Poster owner: Ren.<br>Venue approval: still pending. Do not send the guest email.</blockquote>
<p>Now imagine a saved summary that says: “Ten guests are confirmed for October 18. Kai prepares the poster. Four seats remain. Send the guest email.” That summary is deliberately faulty. It contains older values, and its instruction to send was unsupported even by Version A.</p><p>Make three copies for the exercise: an original brief containing B, a source copy still containing A, and the faulty saved summary. You can do this in a text editor without an AI account. Put the copies side by side and mark which detail first diverges. The date differs between the original and the source copy, so asking another question against A cannot resolve the mismatch.</p><p>If you also try an AI tool, use only these practice notes. Update or replace the source through the route your account offers, then open its contents and look for October 21, 12 guests and Ren. A filename ending in “latest” is not evidence that the contents changed. Stop the exercise if you cannot inspect the source copy.</p></div>
<h2>Use this worked comparison</h2><div data-original="worked-comparison"><div class="table-wrap"><table><thead><tr><th>Detail</th><th>Older saved summary</th><th>Current brief B</th><th>Correction</th></tr></thead><tbody>
<tr><td>Date</td><td>October 18</td><td>2026-10-21</td><td>Use October 21.</td></tr>
<tr><td>Guests</td><td>10 confirmed</td><td>12 confirmed</td><td>Use 12; do not combine counts from both versions.</td></tr>
<tr><td>Poster</td><td>Kai</td><td>Ren</td><td>Replace the owner with Ren.</td></tr>
<tr><td>Seats remaining</td><td>4</td><td>14 capacity minus 12 confirmed</td><td>2, derived from B.</td></tr>
<tr><td>Guest email</td><td>Send it</td><td>Approval pending; do not send</td><td>Keep it as a draft.</td></tr>
</tbody></table></div><p>The remaining-seat calculation must use values from the same applicable version: 14 minus 12 equals 2. Mixing B's date with A's count would create a polished but inconsistent brief. Keep the calculation beside the counts rather than treating a previously generated number as a source fact.</p><p>Write the corrected summary yourself before comparing an AI result: “The workshop is scheduled for October 21, 2026, with 12 confirmed guests and capacity for 14. Two seats remain. Ren owns the poster. Venue approval is pending, so the guest email must stay unsent.” Every claim comes from B or the stated arithmetic.</p></div>
<figure class="editorial-figure"><img src="/assets/editorial/source-update-check.svg" width="760" height="650" loading="lazy" alt="Harbor exercise: October 18 becomes October 21, 10 guests becomes 12, Kai becomes Ren, and remaining seats change from 4 to 2. Email remains unsent."/><figcaption>A fresh date with an old count is still the wrong version.</figcaption></figure>
<h2>Ask again, then update the saved copy</h2><div data-original="update-record"><p>After the source copy matches B, try this request:</p><blockquote>Use only Harbor brief Version B. Write a short workshop update with the date, confirmed guest count, poster owner and approval condition. Calculate remaining seats from B and show the subtraction. Identify B as the source. Do not send an email or invent approval.</blockquote><p>Compare the new answer with the worked summary above. Save it under a different name, such as harbor-brief-B-2026-10-08. Reopen that file independently and check the date, count, owner and unsent-email condition. Repair the destination too if it still contains A's values; correcting the chat does not correct a separately saved file.</p><p>Keep a short change record: previous answer used A; current source inspected as B; date, guests and owner corrected; seats recalculated as 14−12=2; approval remains pending; final file reopened and checked. Record what you actually inspected. If you did not inspect the AI source, write “source version not checked” rather than marking the whole process complete.</p><p>For a real project, keep the change record with the file your team uses. Someone reading only that file should be able to identify the applicable source version. Avoid overwriting the sole earlier copy while a correction is still being reviewed.</p></div>
<h2>Questions about updates</h2><details><summary>Should I delete every old source?</summary><p>No. Preserve history separately and choose the sources that apply to the current task. Do not leave conflicting versions selected without explaining their relationship.</p></details><details><summary>Will asking the same question again fix an old answer?</summary><p>Only if the tool has the applicable source and uses it correctly. Check the source first, then compare the new answer. Update a separately saved file yourself when needed.</p></details><details><summary>What if the refresh option is missing?</summary><p>Check the import route and your access to the original file. Do not apply Drive-specific instructions to an unrelated upload. Record the blocked step and keep the current brief outside the tool until you can verify the import.</p></details>
<p>A <a href="https://www.reddit.com/r/notebooklm/comments/1wxay01/since_drive_autosync_a_notebook_can_be_half_live/" rel="noopener">public discussion about mixed source freshness</a> raises the practical problem of tracking updates. It is a question to investigate, not product documentation.</p><p>Next, <a href="/ai-tools/check-ai-citations/">check whether the cited passage supports the claim</a> and <a href="/ai-tools/check-free-ai-export/">reopen and edit the exported result</a>.</p><h2>Sources and exercise scope</h2><p>Official instructions reviewed 2026-10-08. The Harbor notes, faulty summary, answer key, calculation and diagrams were written for this guide. The exercise demonstrates a way to check versions; it does not measure a product's sync speed or accuracy. Source links are non-affiliate links.</p></article>'''

def publish_freshness_guide(page, cfg):
    page('/ai-tools/check-ai-source-updates/', TITLE+' | '+cfg['brand'], DESCRIPTION, BODY, lastmod='2026-10-08')
