"""Source-grounded newcomer guide with attributed referral evidence."""
MUSE_CARD = '''<article class="card"><p class="eyebrow">PERSONAL AI AGENTS</p><h3><a href="/ai-tools/meta-muse-guide/">Meta Muse: sign up and try a first task</a></h3><p>Learn what an agent does, start with a checkable task, and manage its permissions. Includes our referral code and the owner’s reported reward.</p></article>'''

def publish_muse(page):
    body = '''<section class="page-hero"><p class="eyebrow">PERSONAL AI AGENT · BEGINNER GUIDE</p><h1>Meta Muse: sign up, finish your first task, and understand referrals.</h1><p class="lede">Learn the official entry point, what an agent can do, how to review its work, and how to use our referral code LKN3UO.</p></section>
<article class="prose">
<p><strong>By OuKiki · Reviewed 3 October 2026.</strong> A beginner’s guide based on Meta’s documentation. Referral reward details below come from the site owner.</p>
<nav aria-label="Guide sections"><p><a href="#agent">What Muse does</a> · <a href="#register">Registration</a> · <a href="#first-task">First task</a> · <a href="#referral">Code &amp; rewards</a> · <a href="#privacy">Permissions</a> · <a href="#faq">FAQ</a></p></nav>
<h2 id="agent">What is Muse, and what does an AI agent do?</h2>
<p>Muse is Meta's personal AI agent, powered by Muse Spark. Muse Spark is the underlying model; Muse is the product that uses it to carry out work. Use <a href="https://muse.ai/" rel="noopener">muse.ai</a> to avoid similarly named products. Meta describes a dedicated virtual machine and browser, work across connected applications, and tasks that continue after you close the app. These features are described by Meta. <a href="https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/" rel="noopener">Source: Meta's announcement.</a></p>
<p>A useful distinction: a chatbot may explain how to compare products; an agent may visit their pages and assemble a comparison. You still need to define the job and check the finished work. Browser access does not make an answer automatically correct.</p>
<h2>Potential advantages for a beginner</h2>
<p>Meta's design walkthrough describes document and webpage creation and ongoing goals. It describes the <strong>Goals</strong> tab for following work, an <strong>Ideas</strong> tab for suggestions, and an activity log available through the Muse avatar. <a href="https://introducing.muse.ai/" rel="noopener">Source: How We Designed Muse.</a></p>
<ul><li><strong>Research:</strong> request a comparison with a source beside each factual claim.</li><li><strong>Writing:</strong> turn your own notes into a draft, then check its facts and tone.</li><li><strong>Planning:</strong> request a checklist with a clear finish line.</li><li><strong>Prototypes:</strong> request a small webpage or document you can open and inspect.</li></ul>
<p>Try a task you can review yourself before relying on a longer job. Check the sources and the finished file, not just the progress message.</p>
<h2 id="register">How to register through the official website</h2>
<p><strong>Check eligibility first.</strong> Meta's French Connect announcement dated 24 September 2026 lists the United States, Canada, and Mexico. Availability may have changed since that announcement. Check the current official site for your real region; do not change your identity or account country to obtain access. <a href="https://about.fb.com/fr/news/2026/09/meta-connect-2026-meta-annonce-de-nouvelles-lunettes-ia-des-nouveautes-pour-muse-et-les-meta-vr-glasses/" rel="noopener">Source: Meta Connect.</a></p>
<ol><li>Open <a href="https://muse.ai/" rel="noopener">the official Muse website</a>. During our check, its entry screen offered login or account creation using a phone number or email address, followed by Continue. Wording varies by language.</li><li>Use contact details you control. Read the terms and optional messaging consent before continuing. Handle passwords and verification codes yourself; never send them to this site's contact email.</li><li>Follow the verification and setup screens actually displayed. We checked the entry screen, not a complete new signup; follow the screens shown in your account.</li><li>Review your account's current referral offer before redeeming a code. If it is absent, use official support rather than an unofficial workaround.</li><li>Start with public information. Connect another account only when a task needs it and you understand the access requested.</li></ol>
<p>Meta's help explains the use of email and phone information for account communication and recovery. Keep those details under your control. <a href="https://www.meta.com/help/artificial-intelligence/31983416211257755/" rel="noopener">Source: Meta Help Center.</a></p>
<h2 id="first-task">Your first task: a source-backed comparison</h2>
<p>Choose two public product pages you understand. Aim for a result you can check without granting mailbox access or supplying payment information. Use this suggested prompt:</p>
<blockquote><p>Compare [URL A] and [URL B]. I am a beginner choosing a tool for [my actual task]. Use only public information. Give me a short table, a source URL for every factual claim, and a list of unknowns. Do not create accounts, purchase anything, send messages, or change settings. Stop when the draft is ready for review.</p></blockquote>
<ol><li><strong>Define success:</strong> decide which differences matter before starting.</li><li><strong>Review the plan:</strong> check its proposed actions and narrow unnecessary access.</li><li><strong>Watch progress:</strong> inspect the activity trail and goal where available.</li><li><strong>Open the sources:</strong> confirm names, features, and any prices on the original pages.</li><li><strong>Correct a specific issue:</strong> identify a missing source or wrong assumption and ask for revision.</li><li><strong>Review before sharing:</strong> save the useful output and remove connections you no longer need.</li></ol>
<h2>More starter prompts</h2>
<p><strong>A writing draft:</strong> “Turn these non-sensitive notes into an email draft. Preserve facts, mark missing information, and do not send it.”</p>
<p><strong>A learning plan:</strong> “Build a beginner checklist for [topic] using official documentation. Link the readings, explain a first exercise, and label prerequisites.”</p>
<p><strong>A simple webpage:</strong> “Create a small static page from this public brief. Use no tracking or external services. Explain how to inspect it and identify missing information.”</p>
<p>Replace the brackets with your goal. These are prompts to try, not tasks we ran in Muse.</p>
<h2 id="referral">Referral code LKN3UO and the token reward</h2>
<div class="notice"><strong>Referral disclosure:</strong> this is the site owner's code. We may receive promotional usage credits when an eligible reader uses it. We are independent of Meta; this is not official support or a claim of cash commission.</div>
<p><strong>Our code: <code>LKN3UO</code>.</strong> Visit <a href="https://muse.ai/" rel="sponsored noopener">the official Muse website</a>. This link does not automatically apply the code.</p>
<p><strong>Owner-reported test:</strong> on 3 October 2026, OuKiki confirmed personally testing the referral reward and receiving the advertised <strong>1,000,000,000 tokens (one billion)</strong>. The owner describes the offer as one billion tokens for each side. We have the owner’s confirmation; we have not independently inspected the reward transaction or verified the full promotion terms.</p>
<p><strong>What we could not confirm:</strong> our review of Meta's public announcement, product walkthrough, and Help Center did not locate the complete Muse-specific referral terms. Its terms page required login during our check. We cannot independently confirm today's redemption deadline, code quota, expiry, or eligibility for your account. </p>
<ol><li>Read the offer shown in your Muse account: eligibility, each party's reward, credit timing, and limits.</li><li>If a referral-code field is available, enter <strong>LKN3UO</strong> exactly and review the offer before confirming.</li><li>Check the reward or usage-credit information in your account afterwards. We have not verified its current menu path and do not invent one.</li><li>If no reward appears, keep the on-screen message for official support. Do not publish account details or repeatedly create accounts.</li></ol>
<p>The owner’s reward does not settle your eligibility. These are usage credits, not a promise of cash or unlimited access.</p>
<h2 id="privacy">Permissions and privacy before connecting accounts</h2>
<p>Meta says users control app connections and can disconnect them. Review which accounts the agent can read or change and keep approval for consequential actions. <a href="https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/" rel="noopener">Source: official announcement.</a></p>
<p>Meta's security documentation describes isolated execution, approval controls, and a mailbox connector that filters login codes and password-reset links. It states that the current Secure VM does not prevent Meta accessing data when needed for operation, support, or security; the stronger Confidential VM is described as future work. Settings include a training opt-out. These protections do not make every action error-free. <a href="https://research.meta.ai/blog/security-and-safety-for-ai-agents-our-approach-with-muse" rel="noopener">Source: Meta's security explanation.</a></p>
<p>Our advice: begin without private connections and grant access only for a clear purpose. Treat webpage content as information, not instructions overriding your goal. Do not assume an agent can read a verification code or that a virtual machine hides files from its provider.</p>
<h2 id="faq">Beginner FAQ</h2>
<h3>Do I need programming skills?</h3><p>These starter exercises require a clear request and result review, not writing code. Technical outputs still require appropriate testing.</p>
<h3>Does a referral code replace registration?</h3><p>Follow the official account flow and your displayed offer. We have not verified any rule that a code bypasses region or account checks.</p>
<h3>What is a token, and how long does the reward last?</h3><p>A token is a unit used in model processing, not a fixed number of completed jobs. Without a verified Muse consumption formula or promotion expiry, we cannot convert this credit grant into hours, tasks, or money.</p>
<h3>What if a finished task is wrong?</h3><p>Inspect the actual artifact: open the website, read the document, or follow the source. Request a specific correction. Review messages, purchases, or account changes before approval.</p>
<h3>Why is the referral option or my region missing?</h3><p>This guide cannot determine your eligibility. Follow the official screen and support guidance. Do not buy accounts, invent a country, or share credentials with someone offering to unlock access.</p>
<h2>Sources and what we checked</h2>
<p>We checked the entry screen and the official documentation linked above. The prompts are suggested exercises. The reward report belongs to the owner and has not been independently audited.</p>
<p><a href="https://muse.ai/terms" rel="noopener">Muse terms</a> required login during this check. Review the current terms and Muse-specific promotion in your own account.</p>
<p><a href="/ai-tools/">← All AI tools</a> · <a href="/ai-tools/coding-assistant-checklist/">Evaluate an AI assistant</a></p></article>'''
    page('/ai-tools/meta-muse-guide/', 'Meta Muse Beginner Guide: Sign Up, First Tasks & Referral Code | kikomono-deals', 'Learn Meta Muse registration, agent tasks, permissions and referral code LKN3UO, with the owner-reported token reward and verification limits.', body, lastmod='2026-10-07')
