"""Dated OCR preparation guide; no account actions or affiliate links."""

def publish_pdf_guide(page, cfg):
    page('/ai-tools/scanned-pdf-to-text/',
         'Scanned PDF to text: prepare a document for AI | ' + cfg['brand'],
         'Check whether a PDF needs OCR, choose an extraction route and verify the text before asking AI to summarize it.', '''
<section class="page-hero"><p class="eyebrow">AI OFFICE WORKFLOW</p><h1>Turn a scanned PDF into text you can check</h1><p class="lede">If copying a sentence from your PDF gives no usable text, try OCR before asking AI to summarize it. Verify the extracted text against the page image before trusting the summary.</p></section>
<article class="prose"><p>Reviewed 2026-10-04. This is an official-source workflow guide, not a hands-on product comparison.</p>
<h2>Check what is actually in the file</h2><p>Open a copy in your usual PDF viewer. Select a sentence and paste it into a plain-text document, then search for a distinctive word visible on the page. A scan may contain page images without searchable text; OCR adds recognized text. A failed copy test can also reflect document permissions, so it is a diagnostic clue rather than proof. Do not bypass restrictions on a document you are not allowed to process.</p><p>If the text already copies accurately, skip OCR and check the reading order. If only some pages work, inspect the pages you need individually. Keep the original separate from every converted copy.</p>
<h2>Choose the output before choosing the tool</h2><div class="table-wrap"><table><thead><tr><th>Your goal</th><th>Route to consider</th><th>Check before continuing</th></tr></thead><tbody>
<tr><td>Get editable text from a permitted, non-sensitive scan</td><td>Google Drive conversion to Google Docs</td><td>Cloud upload is acceptable; layout may change</td></tr>
<tr><td>Keep a PDF with searchable text</td><td>Acrobat Scan &amp; OCR</td><td>Your installed edition provides the feature</td></tr>
<tr><td>Merge, split or rotate pages</td><td>Our browser PDF toolbox</td><td>Page organization is separate from recognizing text</td></tr>
</tbody></table></div><p>Do not upload identity documents, customer records or confidential work merely to test an OCR service. Check your organization's rules and the provider's data terms first. This guide makes no claim that every desktop workflow is offline.</p>
<h2>Route A: extract text with Google Drive</h2><p>Google's help page recommends an upright, clear file of 2 MB or less. Upload a permitted copy to Drive, right-click it and choose <strong>Open with &gt; Google Docs</strong>. Compare the converted document with the original. Tables, columns and footnotes may not transfer reliably; do not assume a polished-looking result preserved their meaning. These preparation recommendations come from Google, not our own upload test.</p>
<h2>Route B: make a PDF searchable in Acrobat</h2><p>Adobe documents <strong>All tools &gt; Scan &amp; OCR &gt; In this file</strong>. Select the page range and language, then choose <strong>Recognize Text</strong>. Save a separate output and check it. Adobe describes a searchable text layer and recommends reviewing recognition accuracy. Confirm feature access in your edition before purchasing; this page does not promise free OCR or a particular plan.</p>
<h2>Use a verification sheet before AI</h2><p>Create a small record with four fields: source page, visible wording, extracted wording and correction. Check names, decimal points, minus signs, dates and units wherever they affect your task. For a table, compare each needed value with its row and column headings. If a column is scrambled, manually reconstruct only the relevant rows and label that work as manual correction.</p><p>For example, a table heading may move away from its values during extraction. An AI summary of those values could then attribute them to the wrong category. Checking the source relationship matters more than making the output look tidy.</p>
<h2>Then ask AI a bounded question</h2><p>Use only text you are permitted to share. Add page labels yourself if conversion did not retain them. This reusable prompt is an editorial template, not a tested benchmark:</p>
<blockquote>Summarize only the verified text below for a beginner. Separate facts, uncertainties and next steps. Attach the supplied page label to each factual point. Do not infer missing numbers or headings. If text is unclear, quote the unclear passage and ask for clarification. Do not take actions.</blockquote>
<p>Compare the answer with the verified extraction and the original page. Supplied labels help you check an answer; they do not prove that the assistant independently read the PDF. Correct the extraction before asking for another summary when the error began with OCR.</p>
<h2>When conversion fails</h2><ul><li><strong>Blank or unusable text:</strong> inspect orientation, clarity and whether OCR actually ran.</li><li><strong>Wrong language or characters:</strong> check the recognition language where the tool offers it, then compare again.</li><li><strong>Broken tables:</strong> transcribe the needed data with headings and retain the source page.</li><li><strong>Restricted or confidential file:</strong> stop and use an approved process; do not remove protection as a shortcut.</li></ul>
<p><a href="https://tool.kikomono.com/">Organize pages with our PDF toolbox</a> before working on a copy. Merging or rotating pages does not itself make image text searchable. Continue with <a href="/start/">your first useful AI task</a> or <a href="/ai-tools/verify-ai-meeting-summaries/">the summary-checking workflow</a>.</p>
<h2>Official sources and limits</h2><ul><li><a href="https://support.google.com/drive/answer/176692?hl=en" rel="noopener">Google Drive: convert PDF and photo files to text</a></li><li><a href="https://helpx.adobe.com/in/acrobat/desktop/create-documents/scan-documents-to-pdfs/recognize-text.html" rel="noopener">Adobe: recognize text in scanned documents</a></li></ul><p>Product steps were checked against these official pages on 2026-10-04. The diagnostic and verification checklist is editorial advice. No measured OCR accuracy, guaranteed time saving, discount or affiliate commission is claimed.</p></article>''', lastmod='2026-10-04')

