"""A worked zero, empty and unknown table-export exercise."""
TITLE = "Keep zero, blank and UNKNOWN separate in AI tables"
DESCRIPTION = "Check a saved AI table with a five-row exercise: preserve recorded zero, empty fields and unresolved counts."
BODY = '''<section class="page-hero task-hero"><p class="eyebrow">FREE AI TOOLS / TABLE EXPORTS</p><h1>Zero, blank and UNKNOWN are different.</h1><p class="lede">Before using an AI-generated table, define what each state means and check it again in the saved file. Keep a measured zero as 0, an intentionally empty field empty, and an unresolved value labelled UNKNOWN. Use a separate status column when the destination needs numbers. Do not fill gaps with zero just to make a table look complete.</p></section><article class="prose">
<section class="practice-kit" aria-labelledby="practice-kit-title"><h2 id="practice-kit-title">Try the five-row exercise</h2><p>Download the invented notes, make your own CSV, then compare it with the answer key. Keep the answer separate until you have tried the task.</p><nav class="task-links" aria-label="Practice downloads"><a href="/assets/practice/juniper-notes.txt" download>Download notes (.txt)</a><a href="/assets/practice/juniper-counts.csv" download>Download answer key (.csv)</a><a href="/assets/practice/juniper-checklist.txt" download>Download check record (.txt)</a></nav></section><h2>Agree on the meaning before generating the table</h2><p>Zero can be a real observation. A blank may mean nobody supplied a value, or that a field does not apply. UNKNOWN is a label you choose for an unresolved fact. Those meanings come from your task, not from the appearance of a cell. Tell the assistant the rule and keep it beside the file you will use.</p><p>For a free AI workflow, start with a tiny sample before generating a long table. You can check the sample in a text editor without another AI request. If you use a spreadsheet, inspect the underlying value as well as what the cell displays. A neat layout is not evidence that the original meaning survived.</p>
<figure class="editorial-figure"><img src="/assets/editorial/zero-blank-unknown.svg" width="760" height="650" alt="A recorded zero remains 0. An empty field stays empty with its reason in a status column. An unresolved value stays UNKNOWN, not zero."/><figcaption>Keep the value and its meaning together.</figcaption></figure>
<h2>Practise with five fictional inventory rows</h2><div data-original="fixture"><p>These Juniper cupboard notes are invented. The count is the number of items physically checked today. A row can exist without a count. Do not interpret an unchecked cupboard as empty.</p><blockquote>J1 — cables: checked, count 0.<br>J2 — lamps: not checked, count UNKNOWN.<br>J3 — cups: checked, count 4.<br>J4 — paper: count field intentionally empty; awaiting entry.<br>J5 — clips: checked, count 2.</blockquote><p>Use three columns: item, count and status. For this exercise, UNKNOWN is a literal text token in the count column. A truly empty count field has no characters. The status column explains why it is empty or unresolved. The labels are conventions for these notes, not universal CSV rules.</p><blockquote data-copy-label="Copy prompt">Convert only the Juniper notes to a three-column CSV: item,count,status. Preserve numeric 0 for checked cables, literal UNKNOWN for unchecked lamps, and a genuinely empty count field for paper. Keep the reason in status. Do not infer missing counts, trim away rows or replace blanks with zero. Return the header and five rows, with no additional data.</blockquote></div>
<h2>Compare the saved CSV with this answer key</h2><div data-original="answer"><pre><code>item,count,status
cables,0,checked
lamps,UNKNOWN,not checked
cups,4,checked
paper,,awaiting entry
clips,2,checked</code></pre><p>Save the block as a UTF-8 text file named juniper-counts.csv. Open it in a text editor first. The paper row has two consecutive commas because its middle field is empty. The cables row contains the character 0. The lamps row contains UNKNOWN. A literal space between the commas would be a different field value.</p><div class="table-wrap"><table><thead><tr><th>Row</th><th>Count field</th><th>Meaning</th><th>Reject this change</th></tr></thead><tbody>
<tr><td>Cables</td><td>0</td><td>Checked; none found.</td><td>Hiding or removing the recorded zero.</td></tr>
<tr><td>Lamps</td><td>UNKNOWN</td><td>Not checked yet.</td><td>Replacing it with 0 or dropping the row.</td></tr>
<tr><td>Cups</td><td>4</td><td>Checked count.</td><td>Moving 4 to another item.</td></tr>
<tr><td>Paper</td><td>Empty</td><td>Entry awaited.</td><td>Adding a space, zero or invented count.</td></tr>
<tr><td>Clips</td><td>2</td><td>Checked count.</td><td>Losing the item label.</td></tr>
</tbody></table></div><p>There are five data rows: three checked numeric counts, one UNKNOWN token and one empty field. The known counts add to 6: 0 + 4 + 2. That is the subtotal for checked items, not a complete count of the cupboard. Treating the other two rows as zero would falsely imply that they had been checked.</p></div>
<h2>What we checked locally</h2><p>We saved this exact fictional CSV and read it with Python's standard CSV parser, then wrote and reopened a copy. The count fields remained the strings “0”, “UNKNOWN”, “4”, an empty string and “2”, in that order. That verifies this fixture's text round trip. It does not verify an AI model, Google Sheets import or every export route.</p>
<h2>Check the destination separately</h2><p>Google's <a href="https://support.google.com/docs/answer/3093290?hl=en" rel="noopener">ISBLANK documentation</a> says the function returns FALSE for content including a space, an empty string and hidden characters. A cell that looks empty can therefore behave differently from an empty cell. Use a spare area of your own sheet to inspect the values; do not bulk-clear source data merely to make a test return TRUE.</p><div data-original="destination"><ol><li>Keep the original CSV unchanged and import or paste a copy through the route you intend to use.</li><li>Confirm five rows and the same item labels. Open the cables cell and inspect its value: it must still represent 0.</li><li>Check the lamps token and the paper field separately. If paper contains a space or a formula returning empty text, record that difference instead of calling it a verified empty field.</li><li>If the destination needs a numeric column, leave unresolved numeric entries empty and carry their meanings in status. Preserve the original token-based file so the conversion can be explained.</li><li>Save and reopen the destination. Recheck cables, lamps and paper before sharing the result.</li></ol><p>Write a short acceptance record: source file retained; row labels match; recorded zero preserved; unresolved state retained; empty field inspected; destination reopened. Mark a step untested if you have not performed it. A chat preview cannot complete the destination check.</p></div>
<figure class="editorial-figure"><img src="/assets/editorial/table-state-check.svg" width="760" height="650" loading="lazy" alt="Juniper check: five rows, three checked numbers, one UNKNOWN, one empty field. Known subtotal is 6; a full total remains unavailable."/><figcaption>A subtotal can be correct while the complete total is still unknown.</figcaption></figure>
<section class="practice-kit" aria-labelledby="practice-checks-title"><h2 id="practice-checks-title">Mark the checks you actually completed</h2><p>Leave untested steps unchecked. Marks stay only on this page and reset on reload; download the check record above if you need to retain your results.</p><div class="practice-checklist" data-practice-checklist><label><input type="checkbox"> Original CSV retained.</label><label><input type="checkbox"> Five item labels and rows match.</label><label><input type="checkbox"> Cables keeps the recorded zero.</label><label><input type="checkbox"> Lamps remains UNKNOWN.</label><label><input type="checkbox"> Paper's empty field and its status inspected.</label><label><input type="checkbox"> Destination saved, reopened and checked.</label></div></section><h2>Repair one changed field</h2><div data-original="repair"><p>Suppose an exported copy changes the lamps count to 0. This is a deliberately faulty example. Repair the copy against J2: restore UNKNOWN, keep “not checked” in status and leave the cables zero alone. Log the item and the change. Do not replace every zero with UNKNOWN; the cables observation was valid.</p><p>Now suppose someone checks the lamps and reports 3. Save that new observation with its date and source, update only the lamps row to count 3 and status checked, and retain the earlier file. The checked subtotal becomes 9, but paper still awaits entry. Resolving one row does not resolve every missing value.</p></div>
<h2>Questions about empty values</h2><details><summary>Should every blank become UNKNOWN?</summary><p>No. First define whether it means unresolved, intentionally omitted or not applicable. Use a status field when those states matter.</p></details><details><summary>Can I hide zeros for a cleaner display?</summary><p>Keep the underlying observation and make any display rule explicit. For this acceptance exercise, show the zero so it is easy to check.</p></details><details><summary>Does quoting a CSV field guarantee its spreadsheet type?</summary><p>No. Inspect the destination's import settings and the resulting value. CSV syntax alone does not prove how a particular spreadsheet interpreted a field.</p></details>
<p>A <a href="https://www.reddit.com/r/googlesheets/comments/pzhc6a/" rel="noopener">community question about empty cells being treated as zero</a> shows why these distinctions can matter. It is an individual workflow question, not a product reliability measurement.</p><p>Next, <a href="/ai-tools/check-free-ai-export/">check the whole exported file</a> or <a href="/ai-tools/ask-about-missing-details/">ask about a missing fact</a>.</p><h2>Sources and exercise scope</h2><p>Official documentation reviewed 2026-10-10. Juniper notes, prompt, answer key and illustrations were created for this guide. The local CSV check uses fictional data; no account-level AI or spreadsheet import test is claimed. Source links are direct non-affiliate links.</p></article>'''

def publish_table_state_guide(page,cfg):
    page("/ai-tools/keep-zero-blank-unknown/",TITLE+" | "+cfg["brand"],DESCRIPTION,BODY,lastmod="2026-10-11")
